---
# Build and Deploy the github pages
name: pages
on:
    push:
        branches:
            - main

permissions:
    contents: write

jobs:
    build-and-deploy-pages:
        runs-on: ubuntu-22.04

        strategy:
            matrix:
                node-version: [14.x, 16.x, 18.x]

        steps:
            - name: Checkout thhe code
              uses: actions/checkout@v3

            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v3
              with:
                  node-version: ${{ matrix.node-version }}
                  cache: 'yarn'

            - name: YARN Install
              run: yarn install --immutable

            - name: YARN Clean
              run: yarn clean

            - name: Lint the code
              run: yarn lint

            - name: Build the examples
              run: yarn examples

            - name: Test
              run: yarn test

            - name: Deploy
              uses: JamesIves/github-pages-deploy-action@v4.4.1
              with:
                  branch: gh-pages
                  folder: build/examples
